name = "gleam_bson"
version = "0.19.0"

description = "A bson encoder and decoder written in gleam"
licences = ["Apache-2.0"]
links = [
  {title = "gleam", href = "https://gleam.run"},
  {title = "bson", href = "https://bsonspec.org"},
]
repository = {type = "github", user = "massivefermion", repo = "gleam_bson"}

[dependencies]
gleam_crypto = "~> 0.3"
gleam_stdlib = "~> 0.25"

[dev-dependencies]
gleeunit = "~> 0.7"
