name = "gleam_bson"
target = "erlang"
version = "0.24.0"

description = "bson encoder and decoder for gleam"
licences = ["Apache-2.0"]
links = [
  {title = "gleam", href = "https://gleam.run"},
  {title = "bson", href = "https://bsonspec.org"},
]
repository = {type = "github", user = "massivefermion", repo = "gleam_bson"}

[dependencies]
birl = "~> 0.9"
gleam_crypto = "~> 0.3"
gleam_stdlib = "~> 0.28"

[dev-dependencies]
gleeunit = "~> 0.10"
