name = "bison"
target = "erlang"
version = "1.7.0"

description = "BSON encoder and decoder for Gleam"
gleam = ">= 0.32.0"
licences = ["Apache-2.0"]
links = [
  { title = "Gleam", href = "https://gleam.run" },
  { title = "BSON", href = "https://bsonspec.org" },
]
repository = { type = "github", user = "massivefermion", repo = "bison" }

internal_modules = [
  "bison/kind",
  "bison/encoder",
  "bison/decoder",
  "bison/ejson/*",
]

[dependencies]
birl = "~> 1.8"
gleam_json = "~> 2.0"
gleam_stdlib = ">= 0.49.0 or < 2.0.0"
juno = "~> 1.4"
gleam_deque = ">= 1.0.0 and < 2.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.2"
