name = "bison"
target = "erlang"
version = "0.32.0"

description = "BSON encoder and decoder for Gleam (formerly gleam_bson)"
gleam = ">= 0.32.0"
licences = ["Apache-2.0"]
links = [
  {title = "Gleam", href = "https://gleam.run"},
  {title = "BSON", href = "https://bsonspec.org"},
]
repository = {type = "github", user = "massivefermion", repo = "bison"}

internal_modules = [
  "bison/kind",
  "bison/encoder",
  "bison/decoder",
  "bison/ejson/*",
]

[dependencies]
birl = "~> 0.18"
gleam_json = "~> 0.7"
gleam_stdlib = "~> 0.32"

[dev-dependencies]
gleeunit = "~> 1.0"
