name = "bison"
target = "erlang"
version = "0.29.1"

description = "BSON encoder and decoder for Gleam (formerly gleam_bson)"
licences = ["Apache-2.0"]
links = [
  {title = "gleam", href = "https://gleam.run"},
  {title = "bson", href = "https://bsonspec.org"},
]
repository = {type = "github", user = "massivefermion", repo = "bison"}

gleam = ">= 0.32.0"
internal_modules = [
  "bison/kind",
  "bison/encoder",
  "bison/decoder",
]

[dependencies]
birl = "~> 0.17"
gleam_crypto = "~> 0.4"
gleam_stdlib = "~> 0.32"

[dev-dependencies]
gleeunit = "~> 1.0"
