name = "bison"
target = "erlang"
version = "1.6.0"

description = "BSON encoder and decoder for Gleam"
gleam = ">= 0.32.0"
licences = ["Apache-2.0"]
links = [
  { title = "Gleam", href = "https://gleam.run" },
  { title = "BSON", href = "https://bsonspec.org" },
]
repository = { type = "github", user = "massivefermion", repo = "bison" }

internal_modules = [
  "bison/kind",
  "bison/encoder",
  "bison/decoder",
  "bison/ejson/*",
]

[dependencies]
birl = "~> 1.6"
gleam_json = "~> 1.0"
gleam_stdlib = "~> 0.36 or ~> 1.0"
juno = "~> 1.3"

[dev-dependencies]
gleeunit = "~> 1.1"
