name = "gleam_bson"
version = "0.11.0"

licences = ["Apache-2.0"]
description = "A bson encoder and decoder written in gleam"
repository = { type = "github", user = "massivefermion", repo = "gleam_bson" }
links = [{ title = "bson", href = "https://bsonspec.org" }]

[dependencies]
gleam_stdlib = "~> 0.20"

[dev-dependencies]
gleeunit = "~> 0.6"
